title: "Ragdoll"
theme: jekyll-theme-minimal
description: "Real-time physics for Maya"
logo_title: https://user-images.githubusercontent.com/2152766/95574482-e9a5f500-0a24-11eb-92b0-1f836424efef.png
logo_mascot: https://user-images.githubusercontent.com/2152766/95574486-eb6fb880-0a24-11eb-978f-10652dd82a43.png
repository: "alanjfs/ragdoll-web"
show_downloads: false
markdown: CommonMarkGhPages
ragdoll_version: "2020.11.17"
commonmark:
  extensions: ["autolink"]